"""Build the data the full-universe narrator needs.

Two artifacts, from the real study panel:

  api/_panel.py          A Python module (PANEL = {...}) with the whitelisted,
                         pre-computed fields for EVERY priced event, keyed by
                         "<TICKER>-<year>". This is the SERVER-SIDE source of
                         truth: the narrator looks up trusted numbers here, so a
                         client can never inject facts. Shipped as a module (not
                         a data file) because Vercel's Python bundler reliably
                         includes imported modules, not files opened at runtime.

  docs/panel_index.json  A lightweight index (ticker -> sector + its events with
                         a couple of display fields) for the front-end search /
                         year picker. Display only; the key the client sends is
                         re-validated against PANEL server-side.

Usage: PYTHONPATH=src .venv/Scripts/python.exe scripts/build_web_panel.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from eqd.config import PANEL_DIR

ROOT = Path(__file__).resolve().parents[1]
PANEL_MODULE = ROOT / "api" / "_panel.py"
INDEX_JSON = ROOT / "docs" / "panel_index.json"

# Whitelisted fields the narrator is allowed to see (mirror of memo._EVENT_FIELDS).
FIELDS = [
    "ticker", "sector", "accession", "filing_date", "t0",
    "n_added", "n_removed", "net_added", "doc_similarity",
    "d_tone_negative", "d_tone_uncertainty",
    "market_model__ar_0_1", "market_model__car_0_5", "market_model__car_0_21",
    "market_model__placebo_pre", "beta",
]


def _num(v):
    return v.item() if hasattr(v, "item") else v


def main() -> None:
    panel = pd.read_csv(PANEL_DIR / "study_panel.csv")
    priced = panel.dropna(subset=["market_model__car_0_5"]).sort_values(["ticker", "t0"])

    server: dict[str, dict] = {}
    index: dict[str, dict] = {}

    for _, row in priced.iterrows():
        tk = str(row["ticker"])
        year = str(row["filing_date"])[:4]
        key = f"{tk}-{year}"
        while key in server:                    # rare same-year re-file: keep both
            key += "b"

        server[key] = {f: _num(row[f]) for f in FIELDS if f in row and pd.notna(row[f])}

        entry = index.setdefault(tk, {"sector": str(row.get("sector", "")), "events": []})
        entry["events"].append({
            "key": key,
            "filing_date": str(row["filing_date"]),
            "net_added": _num(row["net_added"]),
            "car_0_5": _num(row["market_model__car_0_5"]),
        })

    # newest first in each company's list
    for e in index.values():
        e["events"].sort(key=lambda x: x["filing_date"], reverse=True)

    PANEL_MODULE.parent.mkdir(parents=True, exist_ok=True)
    header = ('"""Auto-generated by scripts/build_web_panel.py — do not edit by hand.\n'
              'Server-side trusted panel for the full-universe narrator."""\n\n'
              "PANEL = ")
    PANEL_MODULE.write_text(header + json.dumps(server, indent=0, default=str) + "\n",
                            encoding="utf-8")
    INDEX_JSON.write_text(json.dumps(index, separators=(",", ":"), default=str),
                          encoding="utf-8")

    print(f"events:    {len(server)}")
    print(f"companies: {len(index)}")
    print(f"{PANEL_MODULE.relative_to(ROOT)}: {PANEL_MODULE.stat().st_size/1024:.0f} KB")
    print(f"{INDEX_JSON.relative_to(ROOT)}: {INDEX_JSON.stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    main()
