"""Build the diff-passage store the grounded filing-Q&A endpoint answers from.

For each company's MOST RECENT 10-K event, re-diff its Item 1A (Risk Factors)
against the prior year from the cached filings and keep the actual changed
sentences: added, removed, and reworded. The Q&A endpoint (api/ask.py) answers
questions strictly from these passages — so, like the narrator, the LLM can only
describe real, extracted filing text; it never invents.

Output: api/_passages.py  (PASSAGES = {TICKER: {accession, filing_date,
prior_accession, added:[...], removed:[...], modified:[...]}}), a Python module
(reliably bundled by Vercel, unlike a runtime-opened data file).

Usage: PYTHONPATH=src .venv/Scripts/python.exe scripts/build_passages.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

from eqd.config import FILINGS_DIR, PANEL_DIR
from eqd.delta.diff import diff_text
from eqd.ingest.sections import extract_sections

OUT = Path(__file__).resolve().parents[1] / "api" / "_passages.py"

# Caps keep the bundle small and each prompt within a sane context budget.
MAX_PER_LIST = 40           # added / removed
MAX_MODIFIED = 20
MAX_SENT_CHARS = 600        # drop pathological run-ons


def _read_item_1a(cik: str, accession: str) -> str | None:
    d = FILINGS_DIR / str(cik).zfill(10) / accession
    if not d.is_dir():
        return None
    htmls = [p for p in d.iterdir() if p.suffix.lower() in (".htm", ".html")]
    if not htmls:
        return None
    html = htmls[0].read_text(encoding="utf-8", errors="replace")
    return extract_sections(html).get("item_1a")


def _clean(sents: list[str]) -> list[str]:
    out = []
    for s in sents:
        s = " ".join(s.split())
        if 30 <= len(s) <= MAX_SENT_CHARS:
            out.append(s)
    return out


def main() -> None:
    panel = pd.read_csv(PANEL_DIR / "study_panel.csv")
    latest = panel.sort_values("t0").groupby("ticker", as_index=False).tail(1)

    store: dict[str, dict] = {}
    skipped = 0
    for r in latest.itertuples(index=False):
        prior_1a = _read_item_1a(r.cik, r.prior_accession)
        cur_1a = _read_item_1a(r.cik, r.accession)
        if not prior_1a or not cur_1a:
            skipped += 1
            continue
        d = diff_text(prior_1a, cur_1a)
        store[r.ticker] = {
            "sector": r.sector,
            "accession": r.accession,
            "prior_accession": r.prior_accession,
            "filing_date": str(r.filing_date),
            "added": _clean(d.added)[:MAX_PER_LIST],
            "removed": _clean(d.removed)[:MAX_PER_LIST],
            "modified": _clean([cur for _, cur, _ in d.modified])[:MAX_MODIFIED],
        }

    header = ('"""Auto-generated by scripts/build_passages.py — do not edit by hand.\n'
              'Real Item 1A diff passages (added/removed/reworded) for the latest 10-K\n'
              'per company; the grounded Q&A endpoint answers only from these."""\n\n'
              "PASSAGES = ")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + json.dumps(store, indent=0, ensure_ascii=False, default=str) + "\n",
                   encoding="utf-8")

    n_add = sum(len(v["added"]) for v in store.values())
    print(f"companies: {len(store)}  (skipped {skipped} with missing cached text)")
    print(f"avg added/company: {n_add/max(len(store),1):.1f}")
    print(f"{OUT.name}: {OUT.stat().st_size/1024/1024:.2f} MB")


if __name__ == "__main__":
    main()
