"""Vercel serverless function: GET /api/narrate?event=<KEY>

Turns ONE pre-computed filing event into a grounded, cited, no-advice memo.

Why this is safe to expose publicly:
  * `event` must be a key that exists in the pre-computed study panel (all real
    S&P 500 filing events). An unknown key is rejected before any model call, so
    a public URL cannot be coerced into narrating made-up data — the client only
    ever sends a key, never the numbers, which are looked up server-side.
  * Every number in the prompt is a value that was pre-computed by the study
    harness; the model is told to invent nothing and to give no advice.
  * A per-instance rate limiter + a warm-instance cache bound how often the key
    is actually spent.

Model: GLM 5.2 via NVIDIA's OpenAI-compatible endpoint (free on build.nvidia.com).
Env: NVIDIA_API_KEY (set in the Vercel project, not committed).
"""

from __future__ import annotations

import json
import os
import re
import sys
import time
from http.server import BaseHTTPRequestHandler
from urllib.parse import parse_qs, urlparse

from openai import OpenAI

# Server-side trusted panel (api/_panel.py, generated by scripts/build_web_panel.py).
# Imported as a module — Vercel's Python bundler reliably ships traced imports.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _panel import PANEL as _EVENTS  # noqa: E402

MODEL = os.getenv("EQD_NARRATE_MODEL", "z-ai/glm-5.2")
BASE_URL = os.getenv("EQD_LLM_BASE_URL", "https://integrate.api.nvidia.com/v1")

# Same grounding contract as src/eqd/narrate/memo.py (duplicated so the serverless
# bundle stays self-contained and does not import pandas / the whole package).
_SYSTEM = (
    "You write a short, factual memo about one SEC 10-K filing: what changed in its "
    "Risk Factors year over year, and how the stock's abnormal return behaved around "
    "the filing. You are given ALL the numbers pre-computed. Rules, strictly:\n"
    "1. Use ONLY the numbers provided. Never invent, estimate, or compute a new figure.\n"
    "2. Purely descriptive. No buy/sell/hold, no recommendation, no forecast, no advice.\n"
    "3. Cite the accession number as the source.\n"
    "4. Neutral and concise: 3-4 sentences. Abnormal returns are versus an "
    "expected-return model; say 'abnormal return', not 'return'."
)

# --- Per-instance guards (module state persists across warm invocations) ---
_CACHE: dict[str, str] = {}          # event key -> generated memo (free on repeat)
_HITS: list[float] = []              # request timestamps for the token bucket
_MAX_PER_MIN = 20                    # cap model calls per warm instance per minute


def _rate_limited() -> bool:
    now = time.time()
    _HITS[:] = [t for t in _HITS if now - t < 60.0]
    if len(_HITS) >= _MAX_PER_MIN:
        return True
    _HITS.append(now)
    return False


def _memo(key: str, client=None) -> str:
    if key in _CACHE:
        return _CACHE[key]
    facts = _EVENTS[key]
    client = client or OpenAI(base_url=BASE_URL, api_key=os.getenv("NVIDIA_API_KEY"))
    resp = client.chat.completions.create(
        model=MODEL,
        temperature=0.4,
        top_p=1,
        max_tokens=800,
        messages=[{"role": "system", "content": _SYSTEM},
                  {"role": "user", "content":
                   "Write the memo from these computed values:\n" + json.dumps(facts, default=str)}],
    )
    content = resp.choices[0].message.content or ""
    text = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
    _CACHE[key] = text
    return text


class handler(BaseHTTPRequestHandler):
    def _send(self, code: int, payload: dict) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Cache-Control", "public, max-age=86400")
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self) -> None:
        params = parse_qs(urlparse(self.path).query)
        key = (params.get("event") or [""])[0]

        if key == "__list__":                       # health/summary (page searches via the static index)
            tickers = sorted({v["ticker"] for v in _EVENTS.values()})
            self._send(200, {"events": len(_EVENTS), "companies": len(tickers),
                             "sample": tickers[:20]})
            return

        if key not in _EVENTS:                      # the allowlist guard (must be a real computed event)
            self._send(404, {"error": f"unknown event {key!r} — not a computed filing event"})
            return

        if not os.getenv("NVIDIA_API_KEY"):
            self._send(503, {"error": "narrator not configured "
                             "(NVIDIA_API_KEY unset on the server)"})
            return

        if _rate_limited():
            self._send(429, {"error": "rate limit — try again shortly"})
            return

        try:
            memo = _memo(key)
        except Exception as exc:                    # never leak a stack trace
            self._send(502, {"error": f"narrator failed: {type(exc).__name__}"})
            return

        facts = _EVENTS[key]
        self._send(200, {
            "event": key,
            "memo": memo,
            "facts": {"ticker": facts["ticker"], "sector": facts["sector"],
                      "accession": facts["accession"], "filing_date": facts["filing_date"],
                      "net_added": facts["net_added"],
                      "car_0_5": facts.get("market_model__car_0_5"),
                      "car_0_21": facts.get("market_model__car_0_21")},
            "cached": key in _CACHE,
        })
